resources:
- name: github-webhook-resource
  type: time
  check_every: 120h
  source:
    interval: 1m

jobs:
- name: github-webhook
  max_in_flight: 1
  serial: true
  public: true
  plan:
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args:
        - "We've been triggered"
